//All reducer action
export const IS_LOADING = 'IS_LOADING';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ADDRESS = 'USER_ADDRESS';
export const USER_DATA = 'USER_DATA';

export const ADD_DATA = 'ADD_DATA';
export const REMOVE_DATA = 'REMOVE_DATA';
export const INCREASE_PRODUCT_QUANTITY = 'INCREASE_PRODUCT_QUANTITY';
export const DECREASE_PRODUCT_QUANTITY = 'DECREASE_PRODUCT_QUANTITY';
export const REMOVE_ALL_PRODUCTS = 'REMOVE_ALL_PRODUCTS';
export const ADD_WISHLIST = 'ADD_WISHLIST';

export const ORDER_LIST = 'ORDER_LIST';
export const UPDATE_ORDER_LIST = 'UPDATE_ORDER_LIST';
export const INCREASE_ORDER_LIST = 'INCREASE_ORDER_LIST';
export const DECREASE_ORDER_LIST = 'DECREASE_ORDER_LIST';
export const REMOVE_ORDER_LIST = 'REMOVE_ORDER_LIST';
export const ASS_STATUS_ORDER_LIST_DATA = 'ASS_STATUS_ORDER_LIST_DATA';

export const CHANGE_TIME = 'CHANGE_TIME';
