export const Icons = {
  //images
  launch_screen: require('./images/launch_screen.png'),
  onboarding1: require('./images/onboarding1.png'),
  onboarding2: require('./images/onboarding2.png'),
  onboarding3: require('./images/onboarding3.png'),
  logo: require('./images/logo.png'),
  location: require('./images/location.png'),
  experience: require('./images/experience.png'),
  logohome: require('./images/logohome.png'),
  down: require('./images/down.png'),
  ic_location: require('./images/ic_location.png'),
  image: require('./images/image.png'),
  plus: require('./images/plus.png'),
  voice: require('./images/voice.png'),
  image1: require('./images/image1.png'),
  image3: require('./images/image3.png'),
  backArrow: require('./images/backArrow.png'),
  shopping_bag: require('./images/shopping_bag.png'),
  more: require('./images/more.png'),
  cartImage: require('./images/cartImage.png'),
  ic_minus: require('./images/ic_minus.png'),
  ic_plus: require('./images/ic_plus.png'),
  rightArrow: require('./images/rightArrow.png'),
  save: require('./images/save.png'),
  image2: require('./images/image2.png'),
  image4: require('./images/image4.png'),
  offerbg: require('./images/offerbg.png'),
  eyeOff: require('./images/eyeOff.png'),
  eyeOn: require('./images/eyeOn.png'),
  darkFantasy: require('./images/Dark_Fantasy.png'),
  Maggi: require('./images/Maggi.png'),
  parle_g: require('./images/Parle_G.png'),
  // tab bar icons
  home: require('./images/home.png'),
  wishlist: require('./images/star.png'),
  myCart: require('./images/cart.png'),
  notification: require('./images/notification.png'),
  account: require('./images/userIc.png'),

  //icon
  back: require('./images/back.png'),
  cart: require('./images/cart_checkout.png'),
  arrow_green: require('./images/arrow_green.png'),
  delete: require('./images/delete.png'),
  search: require('./images/search.png'),
  createapp: require('./images/createapp.png'),
  ic_card: require('./images/ic_card.png'),
  ic_lock: require('./images/ic_lock.png'),
  ic_plus1: require('./images/ic_plus1.png'),
  ic_right: require('./images/ic_right.png'),
  pay: require('./images/pay.png'),
  paypal: require('./images/paypal.png'),
  ic_close: require('./images/ic_close.png'),
  close: require('./images/close.png'),
  collected: require('./images/collected.png'),
  confirmed: require('./images/confirmed.png'),
  placed: require('./images/placed.png'),
  preparing: require('./images/preparing.png'),
  ready: require('./images/ready.png'),
  ic_dotLine: require('./images/ic_dotLine.png'),
  need: require('./images/need.png'),
  payment_processed: require('./images/Payment_Processed.png'),
  cameraScanner: require('./images/cameraScanner.png'),

  qr: require('./images/qr.png'),
  logout: require('./images/logout.png'),
  camera: require('./images/camera.png'),
  gallery: require('./images/gallery.png'),
  send: require('./images/send.png'),
  clock: require('./images/clock.png'),
  phone: require('./images/phone.png'),
  rate_star: require('./images/rate_star.png'),
  share: require('./images/share.png'),

  heartFill: require('./images/heartFill.png'),
  heart: require('./images/heart.png'),

  employee: require('./images/employee.png'),
  faq: require('./images/faq.png'),
  contact: require('./images/contact.png'),

  store1: require('./storeImage/store1.png'),
  store2: require('./storeImage/store2.png'),
  store_1: require('./storeImage/store_1.png'),
  store_2: require('./storeImage/store_2.png'),
  store_3: require('./storeImage/store_3.png'),
  store_4: require('./storeImage/store_4.png'),

  //banner
  banner: require('./banner/banner.jpg'),
  banner1: require('./banner/banner1.jpg'),
  b1: require('./banner/b1.jpg'),
  b2: require('./banner/b2.jpg'),
  b3: require('./banner/b3.jpg'),
  b4: require('./banner/b4.jpg'),
  b5: require('./banner/b5.jpg'),
  b6: require('./banner/b6.jpg'),
  b7: require('./banner/b7.jpg'),
  b8: require('./banner/b8.jpg'),
  b9: require('./banner/b9.jpg'),

  offer_1: require('./banner/offer_1.png'),
  offer_2: require('./banner/offer_2.png'),
  offer_3: require('./banner/offer_3.png'),
  offer_4: require('./banner/offer_4.png'),
  offer_5: require('./banner/offer_5.png'),
  offer_6: require('./banner/offer_6.png'),

  // Products
  bakery_p_1: {
    p1: require('../assets/storeProducts/BreadBakery/p_1.jpg'),
    p2: require('../assets/storeProducts/BreadBakery/p_2.jpg'),
    p3: require('../assets/storeProducts/BreadBakery/p_3.jpg'),
    p4: require('../assets/storeProducts/BreadBakery/p_4.jpg'),
    p5: require('../assets/storeProducts/BreadBakery/p_5.jpg'),
  },

  chocolate_p_2: {
    p1: require('../assets/storeProducts/Chocolates/p_1.jpg'),
    p2: require('../assets/storeProducts/Chocolates/p_2.jpg'),
    p3: require('../assets/storeProducts/Chocolates/p_3.jpg'),
    p4: require('../assets/storeProducts/Chocolates/p_4.jpg'),
    p5: require('../assets/storeProducts/Chocolates/p_5.jpg'),
    p6: require('../assets/storeProducts/Chocolates/p_6.jpg'),
    p7: require('../assets/storeProducts/Chocolates/p_7.jpg'),
    p8: require('../assets/storeProducts/Chocolates/p_8.jpg'),
    p9: require('../assets/storeProducts/Chocolates/p_9.jpg'),
  },

  diary_p_3: {
    p1: require('../assets/storeProducts/Diary/p_1.jpg'),
    p2: require('../assets/storeProducts/Diary/p_2.jpg'),
    p3: require('../assets/storeProducts/Diary/p_3.jpg'),
    p4: require('../assets/storeProducts/Diary/p_4.jpg'),
    p5: require('../assets/storeProducts/Diary/p_5.jpg'),
  },

  drinks_p_4: {
    p1: require('../assets/storeProducts/Drinks/p_1.jpg'),
    p2: require('../assets/storeProducts/Drinks/p_2.jpg'),
    p3: require('../assets/storeProducts/Drinks/p_3.jpg'),
    p4: require('../assets/storeProducts/Drinks/p_4.jpg'),
    p5: require('../assets/storeProducts/Drinks/p_5.jpg'),
    p6: require('../assets/storeProducts/Drinks/p_6.jpg'),
    p7: require('../assets/storeProducts/Drinks/p_7.jpg'),
    p8: require('../assets/storeProducts/Drinks/p_8.jpg'),
    p9: require('../assets/storeProducts/Drinks/p_9.jpg'),
    p10: require('../assets/storeProducts/Drinks/p_10.jpg'),
    p11: require('../assets/storeProducts/Drinks/p_11.jpg'),
    p12: require('../assets/storeProducts/Drinks/p_12.jpg'),
  },

  chips_p_5: {
    p1: require('../assets/storeProducts/Chips/p_1.jpg'),
    p2: require('../assets/storeProducts/Chips/p_2.jpg'),
    p3: require('../assets/storeProducts/Chips/p_3.jpg'),
    p4: require('../assets/storeProducts/Chips/p_4.jpg'),
    p5: require('../assets/storeProducts/Chips/p_5.jpg'),
    p6: require('../assets/storeProducts/Chips/p_6.jpg'),
    p7: require('../assets/storeProducts/Chips/p_7.jpg'),
  },
  pantry_p_6: {
    p1: require('../assets/storeProducts/Pantry/p_1.jpg'),
    p2: require('../assets/storeProducts/Pantry/p_2.jpg'),
    p3: require('../assets/storeProducts/Pantry/p_3.jpg'),
    p4: require('../assets/storeProducts/Pantry/p_4.jpg'),
    p5: require('../assets/storeProducts/Pantry/p_5.jpg'),
    p6: require('../assets/storeProducts/Pantry/p_6.jpg'),
  },

  gum_p_7: {
    p1: require('../assets/storeProducts/Gum/p_1.jpg'),
    p2: require('../assets/storeProducts/Gum/p_2.jpg'),
    p3: require('../assets/storeProducts/Gum/p_3.jpg'),
    p4: require('../assets/storeProducts/Gum/p_4.jpg'),
    p5: require('../assets/storeProducts/Gum/p_5.jpg'),
    p6: require('../assets/storeProducts/Gum/p_6.jpg'),
    p7: require('../assets/storeProducts/Gum/p_7.jpg'),
    p8: require('../assets/storeProducts/Gum/p_8.jpg'),
    p9: require('../assets/storeProducts/Gum/p_9.jpg'),
    p10: require('../assets/storeProducts/Gum/p_10.jpg'),
    p11: require('../assets/storeProducts/Gum/p_11.jpg'),
    p12: require('../assets/storeProducts/Gum/p_12.jpg'),
    p13: require('../assets/storeProducts/Gum/p_13.jpg'),
  },

  // GIF
  experience_gif: require('./gif/experience.gif'),
};
