export const screenName = {
  SplashScreen: 'SplashScreen',
  OnBoaring: 'onBoarding',
  SelectService: 'SelectService',
  LocationScreen: 'LocationScreen',
  ManualLocationScreen: 'ManualLocationScreen',
  LoadingScreen: 'LoadingScreen',
  bottom_tab_navigator: 'bottom_tab_navigator',
  tabBarName: {
    HomeScreen: 'HomeScreen',
    WishlistScreen: 'WishlistScreen',
    MyCartScreen: 'MyCartScreen',
    Orders: 'Orders',
    Account: 'Account',
  },
  CartScreen: 'CartScreen',
  ProductDetails: 'ProductDetails',
  SearchScreen: 'SearchScreen',
  StoreScreen: 'StoreScreen',
  CreateSingScreen: 'CreateSingScreen',
  EmailScreen: 'EmailScreen',
  CardScreen: 'CardScreen',
  AddCardScreen: 'AddCardScreen',
  CheckoutScreen: 'CheckoutScreen',
  OrdersStatusScreen: 'OrdersStatusScreen',
  UpdateOrder: 'UpdateOrder',
  OrderConfirmation: 'OrderConfirmation',
  EditProfile: 'EditProfile',
  LoginScreen: 'LoginScreen',
  AllProductScreen: 'AllProductScreen',

  // Self Checkout
  SearchStoreScreen: 'SearchStoreScreen',
  StoreListScreen: 'StoreListScreen',
  StartCheckoutScreen: 'StartCheckoutScreen',
  NeedHelpScreen: 'NeedHelpScreen',
  ImageClickScreen: 'ImageClickScreen',
  SelfCheckoutScreen: 'SelfCheckoutScreen',
  OrderConfirmationSelfCheckout: 'OrderConfirmationSelfCheckout',
  ReceiptScreen: 'ReceiptScreen',
  LoadingScreenSelfCheckout: 'LoadingScreenSelfCheckout',
  BardcodeScanner: 'BardcodeScanner',
  SelfCheckoutScreenPayment: 'SelfCheckoutScreenPayment',
  ReviewOrder: 'ReviewOrder',

  //Testing
  Websocket: 'Websocket',
};
